version: '2'

services:
  consul:
    image: progrium/consul
    hostname: "{{ consul_hostname }}"
    ports:
      # Explanation of ports needed: http://stackoverflow.com/a/30692226/1514089
      - "8300:8300" # This is used by servers to handle incoming requests from other agents
      - "8301:8301/tcp" # This is used to handle gossip in the LAN. Required by all agents
      - "8301:8301/udp" # This is used to handle gossip in the LAN. Required by all agents
      - "8302:8302/tcp" # This is used by servers to gossip over the WAN to other servers
      - "8302:8302/udp" # This is used by servers to gossip over the WAN to other servers
      - "8400:8400" # This is used by all agents to handle RPC from the CLI
      - "8500:8500" # This is used by clients to talk to the HTTP API
      - "8600:8600" # Used to resolve DNS queries
      - "53:53/udp"
    restart: always
    command: "{{ consul_command }}"
    mem_limit: "64M"