heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:

#Net
  private_net:
    type: OS::Neutron::Net

#Subnet
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: "10.10.10.0/24"
      dns_nameservers: [ "8.8.8.8", "8.8.4.4" ]
      ip_version: 4

#Router
  private_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: public }
  private_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: private_router }
      subnet: { get_resource: private_subnet }

#Ports
  host1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: private_net }
      fixed_ips:
        - ip_address: 10.10.10.11
  #Floating IPs
  host1_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public

  host1_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: host1_floating_ip }
      server_id: { get_resource: host1 }

  host1:
    type: OS::Nova::Server
    properties:
      image: Ubuntu 16.04 "Xenial Xerus"
      flavor: v2.m2.d5
      networks:
        - port: { get_resource: host1_port }
      key_name: penguinkey
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python

  install_agents:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: |
        #!/bin/bash
        apt-get install htop
