- hosts:
    - docker_cluster
  sudo: yes

  roles:
      - {
        role: emmetog.docker-compose,
        docker_compose_version: "1.7.1"
        }

- hosts:
    - docker_cluster
  sudo: yes
  tasks:
  - name: Cleaning directories
    file:
      path: /home/ubuntu/OpenPenguin
      state: absent
  - name: Cloning project from github
    command: "git clone https://github.com/nyancol/OpenPenguin"

- hosts:
    - docker_cluster_primary
  sudo: yes
  tasks:
  - name: Ensure directory exists
    file:
      path: /home/ubuntu/OpenPenguin
      state: directory

  - name: Run docker-compose up
    command: docker-compose -f /home/ubuntu/OpenPenguin/docker-compose.yml up -d
    environment:
      DOCKER_HOST: ":4000"
