---

- name: Ensure needed directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /containers/docker-compose/

- name: Ensure docker-compose for swarm-agent is up to date
  template:
    src: docker-compose-swarm-agent.yml
    dest: /containers/docker-compose/docker-compose-swarm-agent.yml

- name: Run docker-compose pull
  command: /usr/local/bin/docker-compose -f /containers/docker-compose/docker-compose-swarm-agent.yml --project-name swarm-agent pull

- name: Run docker-compose up
  command: /usr/local/bin/docker-compose -f /containers/docker-compose/docker-compose-swarm-agent.yml --project-name swarm-agent up -d