---

- name: Ensure needed directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /containers/docker-compose/

- name: Ensure docker-compose for consul is up to date
  template:
    src: docker-compose-consul.yml
    dest: /containers/docker-compose/docker-compose-consul.yml

- name: Run docker-compose pull
  command: /usr/local/bin/docker-compose -f /containers/docker-compose/docker-compose-consul.yml --project-name consul pull

- name: Run docker-compose up
  command: /usr/local/bin/docker-compose -f /containers/docker-compose/docker-compose-consul.yml --project-name consul up -d